pipeline {
    agent any

    stages {
        stage ("demo"){
            steps {
                myFunc("Hello from the stage")
            }
        }
    }
}

def myFunc(String myText) {
    echo "myText is set to: ${myText}"
}
